// flow-typed signature: b148bbac175844cbe0690d109e7caac1
// flow-typed version: <<STUB>>/gatsby-remark-images_v^3.0.4/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-images/constants' {
  declare module.exports: any;
}

declare module 'gatsby-remark-images/gatsby-browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-images/constants.js' {
  declare module.exports: $Exports<'gatsby-remark-images/constants'>;
}
declare module 'gatsby-remark-images/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-remark-images/gatsby-browser'>;
}
declare module 'gatsby-remark-images/index' {
  declare module.exports: $Exports<'gatsby-remark-images'>;
}
declare module 'gatsby-remark-images/index.js' {
  declare module.exports: $Exports<'gatsby-remark-images'>;
}
