// flow-typed signature: d56c3112ebef4a6e3f23b77ce3de8bdb
// flow-typed version: <<STUB>>/typography-theme-ocean-beach_v^0.16.18/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typography-theme-ocean-beach'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typography-theme-ocean-beach' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typography-theme-ocean-beach/dist/index' {
  declare module.exports: any;
}

declare module 'typography-theme-ocean-beach/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typography-theme-ocean-beach/dist/index.js' {
  declare module.exports: $Exports<'typography-theme-ocean-beach/dist/index'>;
}
declare module 'typography-theme-ocean-beach/src/index.js' {
  declare module.exports: $Exports<'typography-theme-ocean-beach/src/index'>;
}
